# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Beta CI

on:
    push:
        tags:
            - "v*-*"

jobs:
    publish-core:
        defaults:
            run:
                working-directory: ./core
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: bootstap
              run: npm run bootstrap
              working-directory: .
            - run: npm run lint
            - run: npm run build-js
            - run: npm run build-types
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
                  tag: beta
    publish-cells:
        defaults:
            run:
                working-directory: ./cells
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: bootstap
              run: npm run bootstrap
              working-directory: .
            - run: npm run lint
            - run: npm run build-js
            - run: npm run build-types
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
                  tag: beta
